services:
  - type: web
    name: isd-yolov7-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon
    plan: free
