services:
- type: web
  name: isd-yolov7-app
  runtime: python
  repo: https://github.com/K37VIN/Industry-Safety-Detection-
  plan: free
  envVars:
  - key: FLASK_ENV
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
  autoDeployTrigger: commit
version: "1"
